cloud:
  aws:
    credentials:
      access-key: AKIASORZRPNPWDDN4M4Q
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: bteimages

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080